######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 13 13:25:12 2016
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += Linux.pro
